sources:
  - master_ufo/Geologica.designspace
checkCompatibility: False
# version: 1.010
buildOTF: False
buildWebfont: False
# buildTTF: False
axisOrder:
  - CRSV
  - wght
familyName: "Geologica"
stat:
  - name: Cursive
    tag: CRSV
    values:
    - name: Cursive
      value: 1
    - name: Roman
      value: 0
      # flags: 2
    - name: Auto
      value: 0.5
  - name: Weight
    tag: wght
    values:
    - name: Thin
      value: 100
    - name: ExtraLight
      value: 200
    - name: Light
      value: 300
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
    - name: ExtraBold
      value: 800
    - name: Black
      value: 900

# statFormat4:
#   - name: Upright 
#     flags: 2
#     location:
#       slnt: 0
#       CRSV: 0
#   - name: Italic
#     location:
#       slnt: -12
#       CRSV: 1

cleanUp: False